
password_strava_all = '12345678'
usernames = [
    r'velo19@yandex.com',
    r'cyc1@yandex.com',
    r'cyc2@yandex.com',
    r'abc@yandex.com',
    r'mkm@yandex.com',
    r'zxc@yandex.com',
    r'xcv@yandex.com',
    r'asd@yandex.com',
    r'sdf@yandex.com',
    r'ggg@yandex.com',
    r'qqq@yandex.com',
    r'jjj@yandex.com',
    r'eee@yandex.com',
    r'hhh@yandex.com',
    r'nvb@yan.com',
    r'cyc1@aol.com',
    r'cyc2@aol.com',
    r'cyc3@aol.com',
    r'cyc4@aol.com',
    r'cyc5@aol.com',
    r'cyc6@aol.com',
    r'cyc7@aol.com',
    r'cyc8@aol.com',
    r'cyc9@aol.com',
    r'cy10@aol.com',
    r'cyc11@aol.com',
    r'cyc12@aol.com',
    r'cyc13@aol.com',
    r'cyc14@aol.com',
    r'cyc15@aol.com',
    r'cyc1@gmx.com',
    r'cyc2@gmx.com',
    r'cyc3@gmx.com',
    r'cyc1@yahoo.com',
    r'cyc1@proton.com',
    r'cyc2@proton.com',
    r'cyc3@proton.com',
    r'cyc4@proton.com',
    r'cyc5@proton.com',
    r'cyc6@proton.com',
    r'cyc7@proton.com',
    r'cyc8@proton.com',
    r'cyc9@proton.com',
    r'cyc10@proton.com',
    r'cyc11@proton.com',
    r'cyc12@proton.com',
    r'cyc13@proton.com',
    r'cyc14@proton.com',
    r'cyc15@proton.com',
    r'cyc16@proton.com',
    r'cyc17@proton.com',
    r'cyc18@proton.com',
    r'cyc19@proton.com',
    r'cyc20@proton.com',
    r'cyc21@proton.com',
    r'cyc22@proton.com',
    r'cyc23@proton.com',
    r'cyc24@proton.com',
    r'cyc25@proton.com',
]
username_backup = r'kev_backup@yahoo.com'
password_backup_yahoo = r'1357Backup!'
password_cool_tables_yahoo = '1357Worker!'
